language: go

# needed for the nfpm pipe
addons:
  apt:
    packages:
    - rpm

services:
  - redis-server

go:
  - 1.12.x
  - master

env:
  - GO111MODULE=on

install: true

# Fix this by renaming the directory before testing.
# https://github.com/travis-ci/travis-ci/issues/4573
script:
  - export GOBIN="$GOPATH/bin"
  - export PATH="$PATH:$GOBIN"
  # Fix dir names
  - cd $GOPATH/src/github.com/
  - mv Clivern/Rabbit Clivern/rabbit
  - mv Clivern clivern
  - cd clivern/rabbit
  # Config & execute ci tasks
  - make install_revive
  - make ci
  # Workaround to clear any package used for testing only
  - git status
  - git diff > diff.log
  - cat diff.log
  - git clean -fd
  - git reset --hard

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL http://git.io/goreleaser | bash
  on:
    tags: true
    go: 1.12.x
    condition: $TRAVIS_OS_NAME = linux
